import { StyleSheet } from 'react-native';

export const processingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingTop: 20,
    backgroundColor: '#1976d2',
  },
  headerCenterRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  headerCenterColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  headerBackButtonText: {
    fontSize: 14,
    color: 'white',
    fontWeight: '600',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    minWidth: 52,
    justifyContent: 'flex-end',
  },
  headerActionButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    marginRight: 12,
  },
  headerActionButtonText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '600',
  },
  headerBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  titleInline: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'white',
    marginRight: 8,
  },
  headerInfoInline: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
    fontWeight: '500',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  stepTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  stepSubtitle: {
    fontSize: 14,
    color: '#666',
    marginBottom: 15,
    fontStyle: 'italic',
  },
  scanHintBlock: {
    backgroundColor: 'white',
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  scanHintText: {
    fontSize: 14,
    color: '#444',
    lineHeight: 20,
  },
  listScroll: {
    flex: 1,
  },
  itemButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    minHeight: 60,
  },
  itemButtonContent: {
    flex: 1,
  },
  itemButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  itemButtonSubtext: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  itemButtonArrow: {
    fontSize: 24,
    color: '#999',
    marginLeft: 10,
  },
  effectWarningText: {
    fontSize: 12,
    color: '#4caf50',
    fontWeight: '600',
    marginTop: 4,
  },
  emptyText: {
    fontSize: 14,
    color: '#777',
    textAlign: 'center',
    paddingVertical: 16,
  },
  processingPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
  },
  processingPlaceholderText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  processingContainer: {
    paddingBottom: 40,
  },
  formulaRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  formulaBlock: {
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  formulaBlockHalf: {
    flex: 1,
    backgroundColor: 'white',
    padding: 16,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
    marginBottom: 16,
  },
  formulaBlockHalfLeft: {
    marginRight: 8,
  },
  formulaBlockHalfRight: {
    marginLeft: 8,
  },
  formulaTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 12,
  },
  inputGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  resourceIcon: {
    width: 32,
    height: 32,
    marginRight: 8,
  },
  resourceInfo: {
    flex: 1,
  },
  resourceName: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  numberInputCompact: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 16,
    backgroundColor: 'white',
    minWidth: 80,
    maxWidth: 120,
    textAlign: 'center',
  },
  maxLabel: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  maxButton: {
    backgroundColor: '#1976d2',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 6,
    marginLeft: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  maxButtonText: {
    fontSize: 12,
    color: 'white',
    fontWeight: '600',
  },
  calculateButton: {
    backgroundColor: '#1976d2',
    padding: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  calculateButtonSecondary: {
    backgroundColor: '#4caf50',
  },
  calculateButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  resultsContainer: {
    marginTop: 10,
  },
  resultBlock: {
    backgroundColor: '#e3f2fd',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
  },
  resultTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1976d2',
    marginBottom: 10,
  },
  resultText: {
    fontSize: 16,
    color: '#333',
    marginBottom: 5,
  },
  multiContainer: {
    flex: 1,
    padding: 20,
  },
  multiHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  multiHintText: {
    fontSize: 14,
    color: '#444',
    flex: 1,
    marginRight: 12,
  },
  multiClearButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 6,
    backgroundColor: '#e53935',
  },
  multiClearButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  multiScroll: {
    flex: 1,
  },
  multiCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  multiCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  multiCardTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#223',
  },
  multiCardSubtitle: {
    fontSize: 13,
    color: '#666',
    marginTop: 2,
  },
  multiCardInfo: {
    flex: 1,
    paddingRight: 12,
  },
  multiCardRemove: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: '#f44336',
  },
  multiCardRemoveText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  multiSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  multiSectionSubtitle: {
    fontSize: 13,
    color: '#666',
    marginBottom: 12,
  },
  multiInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  multiInputLabel: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  multiInputField: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 16,
    minWidth: 90,
    textAlign: 'center',
    backgroundColor: 'white',
  },
  multiExtractionBlock: {
    backgroundColor: '#f5faff',
    borderRadius: 10,
    padding: 12,
  },
  multiResultsBlock: {
    marginTop: 12,
    backgroundColor: '#e3f2fd',
    borderRadius: 10,
    padding: 12,
  },
  multiResultsTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1976d2',
    marginBottom: 8,
  },
  multiTotalsBlock: {
    marginTop: 20,
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  multiTotalsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1976d2',
    marginBottom: 12,
  },
  multiButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  multiButton: {
    flex: 1,
    backgroundColor: '#1976d2',
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 10,
  },
  multiButtonText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '600',
  },
  multiTotalsSection: {
    marginBottom: 10,
  },
  multiPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  multiPlaceholderText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 22,
  },
  table: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: 'white',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#dbe8ff',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  tableHeaderCell: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a2a4a',
  },
  tableRow: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: '#eef2f7',
  },
  tableCell: {
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingRight: 12,
  },
  tableColName: {
    flex: 0.35,
  },
  tableColInput: {
    flex: 0.25,
  },
  tableColResult: {
    flex: 0.3,
  },
  tableColAction: {
    flex: 0.1,
    alignItems: 'flex-end',
  },
  tableNameText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#223',
  },
  tableInputList: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  tableInputItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f3f7ff',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 10,
    marginBottom: 10,
  },
  tableInputImage: {
    width: 32,
    height: 32,
    marginRight: 6,
  },
  tableInputField: {
    minWidth: 60,
    maxWidth: 100,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#c6d4f2',
    backgroundColor: 'white',
    textAlign: 'center',
    fontSize: 14,
  },
  tableMaxButton: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#1976d2',
    borderRadius: 6,
  },
  tableMaxButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  tableResultList: {
    marginBottom: 4,
  },
  tableActionButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: '#f44336',
    borderRadius: 8,
  },
  tableActionButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
});

export type ProcessingStyles = typeof processingStyles;
