// This file is auto-generated by era_scripts/start-dev.sh on Сб 07 фев 2026 09:49:02 MSK
// Default values are used when running without the script
export const CONFIG = {
  BACKEND_URL: 'http://192.168.1.101:3000',
  BASIC_AUTH: undefined as { username: string; password: string } | undefined,
};
