// This file is auto-generated by era_scripts/start-dev.sh on Чт 30 окт 2025 04:52:27 MSK
// Default values are used when running without the script
export const CONFIG = {
  BACKEND_URL: 'http://192.168.1.101:3000',
};
