// This file is auto-generated by era_scripts/start-dev.sh on Пт 24 окт 2025 22:26:03 MSK
// Default values are used when running without the script
export const CONFIG = {
  BACKEND_URL: 'http://192.168.1.101:3000',
};
